### ISSUE TITLE
What about Svelte 5?

### ISSUE THREAD

**Issue by frederikhors** [paoloricciuti/sveltekit-search-params#79]
Are you working on a Svelte 5 version?

**Comment by paoloricciuti** [comment]
Hi, i'm not actively working on it since the `page` store in sveltekit will still be a store for the foreseeable future.

However i'm starting to think about how to convert to runes since it will probably involve some API redesign at least for `queryParam` since with runes it's not possible to return primitive values and you would be stuck to have something like this

```svelte
<script>
    import { queryParam } from "sveltekit-search-params";

    const user = queryParam("user");
</script>

<input bind:value={user.value} />
```
which kinda defies the meaning where you can just use `queryParameters` like this
```svelte
<script>
    import { queryParameters } from "sveltekit-search-params";

    const params = queryParameters({ user: true, });
</script>

<input bind:value={params.user} />
```
and have the same fine grained reactivity.

So either i would bump to v3 and remove queryParam or i'm thinking of some API like this

```svelte
<script>
    import { queryParam } from "sveltekit-search-params";

    const [user, setUser, userInput] = $derived.by(queryParam("user"));
</script>

<input {...userInput} />
```
where you would use `user` to read the value, `setUser` to set it (maybe i can also do something like `user("value")` to set it) and `userInput` to spread it on an input to handle the update of a value from an input.

I will update this library to runes for sure tho.
